language: objective-c
os: osx
osx_image: xcode7
xcode_workspace: Volkswagen.xcworkspace
xcode_scheme: Volkswagen-iOS

script: xcodebuild -workspace Volkswagen.xcworkspace -scheme Volkswagen-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' test
